### ISSUE TITLE
just to let you know

### ISSUE THREAD

**Issue by loordgek** [Bitterholz/LP2#6]
Krapht is also working on a new version https://github.com/Krapht/LogisticsPipesRedux
maybe you can work w/ him

**Comment by Bitterholz** [comment]
@loordgek Id love to wok with him together! I have a lot of ideas for this and allready put quite a lot of work into Models and textures. Maybe Krapht and I can come to a point of working together. We shall see.

If he denies, ill definitly go on with this one.

**Comment by loordgek** [comment]
cool

**Comment by Bitterholz** [comment]
Krapht is much as before, way to buisy to work on his mod. Both projects have been linked on the original Logistics Pipes Github page.

This issue is hereby closed.
